server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/usuarios_db
spring.datasource.username=app_user
spring.datasource.password=app_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
app.jwt.secret=miClaveSecretaMuyLargaParaHMAC256BitsMinimo1234567890
app.jwt.expiration=86400000
